name: Automate my Semana
on:
  push:
  workflow_dispatch:  
  schedule:
    - cron: "30 0 * * 1"
jobs:
  curl-post:
    runs-on: ubuntu-latest
    env:
      DESK_ID_0: ${{ secrets.DESK_ID_0 }}
      DESK_ID_1: ${{ secrets.DESK_ID_1 }}
      DESK_ID_2: ${{ secrets.DESK_ID_2 }}
      DESK_ID_3: ${{ secrets.DESK_ID_3 }}
      DESK_ID_4: ${{ secrets.DESK_ID_4 }}
      STATUS_0: ${{ secrets.STATUS_0 }}
      STATUS_1: ${{ secrets.STATUS_1 }}
      STATUS_2: ${{ secrets.STATUS_2 }}
      STATUS_3: ${{ secrets.STATUS_3 }}
      STATUS_4: ${{ secrets.STATUS_4 }}
    steps:
      - name: Get my place on semana for all days
        id: loop
        run: |
          echo "Looping over days"
          echo "${{ toJson(steps.loop.outputs) }}"
          for i in {0..5}; do
            day=$(date --date="3 weeks $i days" +%Y-%m-%d)
            if [ $(date -d "$day" +%u) -le 5 ]; then
              echo "Processing day '$day'"
              desk="DESK_ID_$i"
              echo "test '$desk'"
              desk_id_specific=$(env | grep "^$desk=" | cut -d '=' -f2-)
              if [ -n "$desk_id_specific" ]; then
                  desk_id=$desk_id_specific
              else
                  desk_id=${{secrets.DESK_ID}}
              fi
              status="STATUS_$i"
              echo "test '$status'"
              status_specific=$(env | grep "^$status=" | cut -d '=' -f2-)
              if [ -n "$status_specific" ]; then
                  desk_id=$status_specific
              else
                  desk_id=${{secrets.STATUS}}
              fi
              curl 'https://app.semana.io/api/bookings/' \
                -H 'authority: app.semana.io' \
                -H 'accept: */*' \
                -H 'accept-language: fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7' \
                -H 'cache-control: no-cache' \
                -H 'content-type: application/json' \
                -H 'cookie: ${{ secrets.COOKIE }}' \
                -H 'origin: https://app.semana.io' \
                -H 'pragma: no-cache' \
                -H 'referer: https://app.semana.io/${{ secrets.COMPANY }}/floorplan?d=$day&f=740' \
                -H 'sec-ch-ua: "Not_A Brand";v="8", "Chromium";v="120", "Google Chrome";v="120"' \
                -H 'sec-ch-ua-mobile: ?0' \
                -H 'sec-ch-ua-platform: "Linux"' \
                -H 'sec-fetch-dest: empty' \
                -H 'sec-fetch-mode: cors' \
                -H 'sec-fetch-site: same-origin' \
                -H 'user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36' \
                -H 'x-client-version: 2.53.0' \
                --data-raw '{"collaboratorId":'${{ secrets.COLLABORATOR_ID }}',"type":"office","date":"'$day'","deskId":"'$desk_id'","period":"day"}' \
                --compressed
            fi
          done
